### ISSUE TITLE
模拟故障1节点时查询其它节点必crash

### ISSUE THREAD

**Issue by seanlook** [chengshiwen/influxdb-cluster#3]
3 meta-node, 4 data-node，写入设置`--replication-factor=2`

此时 stop 1 个 influxd，在其它节点查询时 节点会一个个全 crash 掉，必现

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x9a1650]

goroutine 25225082 [running]:
github.com/influxdata/influxdb/query.Iterators.Close(0xc05c47e7c0, 0x1, 0x2, 0xc004348a00, 0x2531498)
        /root/influxdb/query/iterator.go:48 +0x50
github.com/influxdata/influxdb/coordinator.(*ClusterShardMapping).CreateIterator(0xc0043489b0, 0x253aee0, 0xc047f69290, 0xc004348a00, 0x2531498, 0xc047f694a0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/influxdb/coordinator/shard_mapper.go:469 +0x445
github.com/influxdata/influxdb/query.(*exprIteratorBuilder).callIterator.func1(0xc0064ad940, 0x253aee0, 0xc047f69290, 0xc0064abc48, 0xc0064abc00, 0xc047f694a0, 0x7f, 0x1279e25)
        /root/influxdb/query/select.go:583 +0x535
github.com/influxdata/influxdb/query.(*exprIteratorBuilder).callIterator(0xc00059d940, 0x253aee0, 0xc047f69290, 0xc047f694a0, 0x2531498, 0xc047f694a0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/influxdb/query/select.go:608 +0xe5
github.com/influxdata/influxdb/query.(*exprIteratorBuilder).buildCallIterator.func1(0xc047f694a0, 0x253aee0, 0xc047f69290, 0xc00059d940, 0xc00059cd20, 0xc00cdb3860, 0x250da80, 0x250da60, 0xc036229aa0)
        /root/influxdb/query/select.go:515 +0xe5
github.com/influxdata/influxdb/query.(*exprIteratorBuilder).buildCallIterator(0xc0064ad940, 0x253aee0, 0xc047f69290, 0xc047f694a0, 0x7f07a5581338, 0xc00d2df9c0, 0x866349, 0xc04593cd50)
        /root/influxdb/query/select.go:559 +0x745
github.com/influxdata/influxdb/query.buildExprIterator(0x253aee0, 0xc047f69290, 0x2531498, 0xc047f694a0, 0x7f08202f3848, 0xc0043489b0, 0xc015582d10, 0x1, 0x1, 0x2531498, ...)
        /root/influxdb/query/select.go:156 +0x285
github.com/influxdata/influxdb/query.buildFieldIterator(0x253aee0, 0xc047f69290, 0x2531498, 0xc047f694a0, 0x7f08202f3848, 0xc0043489b0, 0xc015582d10, 0x1, 0x1, 0x0, ...)
        /root/influxdb/query/select.go:870 +0x4b6
github.com/influxdata/influxdb/query.buildCursor.func1(0x0, 0x0)
        /root/influxdb/query/select.go:744 +0x12b
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc047f694d0, 0xc003ac0af0)
        /root/go/pkg/mod/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
        /root/go/pkg/mod/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:54 +0x66
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x9a1650]
```

**Comment by chengshiwen** [comment]
收到，感谢，我确认下，v1.8.10-c1.0.0 版本，当有 datanode 宕机时，确实会存在查询可能失败出异常的情况，这个问题已经被注意到，将在 v1.8.10-c1.1.0 修复

**Comment by chengshiwen** [comment]
influxdb cluster [v1.8.10-c1.1.0](https://github.com/chengshiwen/influxdb-cluster/releases/tag/v1.8.10-c1.1.0) 正式发布，对上述问题进行了修复，欢迎使用👏🏻
